name: webapp
description: Birthday List Signups.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.1
  auto_size_text: ^2.1.0
  equatable: ^1.2.5
  responsive_builder: 0.3.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_storage: ^5.0.1
  cloud_firestore: ^0.14.3
  flutter_datetime_picker: ^1.4.0
  uuid: ^2.2.2
  clipboard: 0.1.2+8
  extended_image: ^1.3.0
  google_sign_in: ^4.5.9
  intl: 0.16.1
  firebase_auth_oauth: 0.2.2
  flutter_facebook_login_web: 0.2.1+1
  reactive_forms: 7.6.2
  websafe_svg: 1.1.4
  device_info: 1.0.0
  package_info: 0.4.3+2
  qr_flutter: 3.2.0
  credit_card_validator: 1.1.0
  stripe_sdk: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/images/placeholderImages/
    - assets/icons/
  fonts:
    - family: montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 900
    - family: cocon
      fonts:
        - asset: assets/fonts/Cocon-RegularTR.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

